---
title: "Fuel Economy API Practice"
author: "Benzon Carlitos Salazar"
date: "September 16, 2022"
---

<style>
.main-container {
    width: 100%;
    max-width: unset;
}
</style>

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
# install.packages(c("httr", "jsonlite"))
library(magrittr)
```

# Example 2: Vehicle Information

## Build URL

```{r build_urls}
base_url <- "www.fueleconomy.gov/ws/rest/"

# will result in a 404 due to redundant rest/
# info_url <- "rest/vehicle/menu/options?year=2012&make=Honda&model=Fit" 

info_url <- "vehicle/menu/options?year=2012&make=Honda&model=Fit" 
full_url <- paste0(base_url, info_url)
```

## Call API

```{r api_call}
api_call <- httr::GET(full_url)
```

## Check Response

```{r check_response}
api_call$status_code

api_call$content
```

## Convert response to usable data

Interestingly, the API JSON is already in a data frame.

```{r convert}
api_char <- rawToChar(api_call$content)

apiJSON <- jsonlite::fromJSON(api_char, flatten = TRUE)

str(apiJSON$menuItem)
apiJSON$menuItem
```
